[theme]
primaryColor = "#4A90E2"         # EduGenie blue
backgroundColor = "#F9FAFB"      # Light gray background
secondaryBackgroundColor = "#FFFFFF"
textColor = "#1F2937"            # Dark gray text
font = "sans serif"
